server:
  port: 8080

spring:
  boot:
    admin:
      client:
        url: http://localhost:40000

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
  server:
    servlet:
      context-path: /monitor
    port: 8081

